name: CI/CD Pipeline to deploy Laravel PHP App on the hosting infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      - master

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  web-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - name: 🚚 Getting the latest code version on the master branch
        uses: actions/checkout@v3

      # Use NodeJs 16 Engine to run actions
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # install all laravel app php dependencies
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
 
      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Install and build Artefacts
        run: | 
          npm install 
          npm run build

      - name: Run App Test suite 
        run: php artisan test
